"""add table profile settings

Revision ID: 2b2894b61ad0
Revises: 68abe7b09fbe
Create Date: 2025-06-29 20:19:21.185997

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b2894b61ad0"
down_revision: Union[str, None] = "68abe7b09fbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_settings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "is_verification_email",
            sa.Boolean(),
            server_default=sa.text("'false'"),
            nullable=False,
            comment="Подтвеждение email",
        ),
        sa.Column("user_timezone", sa.String(length=50), nullable=False),
        sa.Column(
            "is_notification_email",
            sa.Boolean(),
            server_default=sa.text("'true'"),
            nullable=False,
            comment="Разрешить отправку уведомлений на почту да/нет",
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["profile.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        schema="profile",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profile_settings", schema="profile")
    # ### end Alembic commands ###
