"""init_notification_tables

Revision ID: 87e12665f9ea
Revises: 14449df71b25
Create Date: 2025-07-04 20:55:03.528685+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "87e12665f9ea"
down_revision: Union[str, None] = "14449df71b25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mass_notification",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Уникальный идентификатор массовой рассылки",
        ),
        sa.Column(
            "method",
            sa.String(length=50),
            nullable=False,
            comment="Канал отправки уведомлений (email, push и т.д.)",
        ),
        sa.Column(
            "source",
            sa.String(length=50),
            nullable=False,
            comment="Источник события, вызвавшего рассылку",
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="Текущее состояние рассылки",
        ),
        sa.Column(
            "target_start_sending_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="Планируемое время начала рассылки",
        ),
        sa.Column(
            "start_sending_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Фактическое время начала рассылки",
        ),
        sa.Column(
            "actual_sent_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Фактическое время завершения рассылки",
        ),
        sa.Column(
            "priority",
            sa.String(length=50),
            nullable=False,
            comment="Приоритет рассылки",
        ),
        sa.Column(
            "event_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Дополнительные данные события для шаблона рассылки",
        ),
        sa.Column(
            "template_id",
            sa.Uuid(),
            nullable=True,
            comment="ID шаблона рассылки",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="notification",
    )
    op.create_table(
        "notification",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Уникальный идентификатор уведомления",
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="ID пользователя, которому предназначено уведомление",
        ),
        sa.Column(
            "method",
            sa.String(length=50),
            nullable=False,
            comment="Канал отправки уведомления (email, push и т.д.)",
        ),
        sa.Column(
            "source",
            sa.String(length=50),
            nullable=False,
            comment="Источник события, вызвавшего уведомление",
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="Текущее состояние уведомления",
        ),
        sa.Column(
            "target_sent_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="Планируемое время отправки уведомления",
        ),
        sa.Column(
            "actual_sent_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Фактическое время отправки уведомления",
        ),
        sa.Column(
            "added_queue_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Время постановки уведомления в очередь на отправку",
        ),
        sa.Column(
            "priority",
            sa.String(length=50),
            nullable=False,
            comment="Приоритет уведомления",
        ),
        sa.Column(
            "event_type",
            sa.String(length=100),
            nullable=False,
            comment="Тип уведомления (действие/ситуация, которые привели к отправке уведомления)",
        ),
        sa.Column(
            "event_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Дополнительные данные события для шаблона уведомления",
        ),
        sa.Column(
            "user_timezone",
            sa.String(length=50),
            nullable=True,
            comment="Часовой пояс пользователя",
        ),
        sa.Column(
            "template_id",
            sa.Uuid(),
            nullable=True,
            comment="ID шаблона уведомления",
        ),
        sa.Column(
            "mass_notification_id",
            sa.Uuid(),
            nullable=True,
            comment="ID массовой рассылки, если уведомление массовое",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="notification",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification", schema="notification")
    op.drop_table("mass_notification", schema="notification")
    # ### end Alembic commands ###
